name: OCI Token Exchange Workflow

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  oci-token-exchange:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Debug inputs
        run: |
          echo "OIDC_CLIENT_ID = ${{ secrets.OIDC_CLIENT_ID }}"
          echo "DOMAIN_BASE_URL = ${{ github.variables.DOMAIN_BASE_URL }}"
          echo "OCI_TENANCY = ${{ github.variables.OCI_TENANCY }}"
          echo "OCI_REGION = ${{ github.variables.OCI_REGION }}"

      - name: Exchange OIDC JWT for OCI Token
        id: oci_token_exchange
        uses: gtrevorrow/oci-token-exchange-action@v1
        with:
          oidc_client_identifier: ${{ secrets.OIDC_CLIENT_ID }}
          domain_base_url: ${{ github.variables.DOMAIN_BASE_URL }}
          oci_tenancy: ${{ github.variables.OCI_TENANCY }}
          oci_region: ${{ github.variables.OCI_REGION }}

      - name: Show OCI Token
        run: |
          echo "OCI Access Token:"
          echo "${{ steps.oci_token_exchange.outputs.oci_access_token }}"



