name: OCI Token Exchange via GitHub OIDC

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  exchange-token:
    runs-on: ubuntu-latest
    env:
      CLIENT_ID: ${{ secrets.OCI_CLIENT_ID }}
      CLIENT_SECRET: ${{ secrets.OCI_CLIENT_SECRET }}
      PUBLIC_KEY: ${{ secrets.OCI_PUBLIC_KEY }}

    steps:
      - name: Obter ID Token do GitHub OIDC
        id: oidc
        run: |
          echo "Solicitando token OIDC..."
          TOKEN_JSON=$(curl -sSL "$ACTIONS_ID_TOKEN_REQUEST_URL" \
            -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN")

          ID_TOKEN=$(echo "$TOKEN_JSON" | jq -r .value)
          echo "::add-mask::$ID_TOKEN"
          echo "ID_TOKEN=$ID_TOKEN" >> $GITHUB_ENV

          echo "Token JWT OIDC recebido com sucesso."

      - name: Fazer Token Exchange (JWT → UPST)
        id: upst
        run: |
          echo "Trocando token via Identity Domain da OCI..."

          TOKEN_RESPONSE=$(curl -s -X POST \
            "https://idcs-c3fbb3ae829b4af0a98995e5f1549f09.identity.oraclecloud.com/oauth2/v1/token" \
            -H "Content-Type: application/x-www-form-urlencoded;charset=utf-8" \
            --data-urlencode "grant_type=urn:ietf:params:oauth:grant-type:token-exchange" \
            --data-urlencode "subject_token_type=urn:ietf:params:oauth:token-type:jwt" \
            --data-urlencode "requested_token_type=urn:oci:token-type:oci-upst" \
            --data-urlencode "subject_token=$ID_TOKEN" \
            --data-urlencode "public_key=$PUBLIC_KEY" \
            -u "$CLIENT_ID:$CLIENT_SECRET")

          echo "Resposta do Token Exchange:"
          echo "$TOKEN_RESPONSE" | jq

          ACCESS_TOKEN=$(echo "$TOKEN_RESPONSE" | jq -r '.access_token')

          if [ "$ACCESS_TOKEN" = "null" ] || [ -z "$ACCESS_TOKEN" ]; then
            echo "Falha ao obter o token UPST"
            exit 1
          fi

          echo "::add-mask::$ACCESS_TOKEN"
          echo "UPST=$ACCESS_TOKEN" >> $GITHUB_ENV

      - name: Testar chamada na API OCI com o UPST
        run: |
          echo "Chamando API da OCI com o UPST..."
          curl -s -X GET \
            -H "Authorization: Bearer $UPST" \
            -H "Content-Type: application/json" \
            "https://identity.us-ashburn-1.oraclecloud.com/20160918/users/" | jq

