name: OCI Token Exchange via GitHub OIDC

on:
  workflow_dispatch:  # você pode disparar manualmente no GitHub

permissions:
  id-token: write     # necessário para gerar o OIDC token
  contents: read

jobs:
  exchange-token:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Obter ID Token do GitHub OIDC
        id: oidc
        run: |
          echo "Solicitando token OIDC..."
          TOKEN_JSON=$(curl -sSL "$ACTIONS_ID_TOKEN_REQUEST_URL" \
            -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN")
          ID_TOKEN=$(echo "$TOKEN_JSON" | jq -r .value)

          echo "::add-mask::$ID_TOKEN"
          echo "ID_TOKEN=$ID_TOKEN" >> $GITHUB_ENV

      - name: Fazer Token Exchange na OCI para obter UPST
        id: upst
        run: |
          echo "Trocando token via Identity Domain da OCI..."
          
          TOKEN_RESPONSE=$(curl -s -X POST \
            "https://idcs-c3fbb3ae829b4af0a98995e5f1549f09.identity.oraclecloud.com/oauth2/v1/token" \
            -H "Content-Type: application/x-www-form-urlencoded;charset=utf-8" \
            --data-urlencode "grant_type=urn:ietf:params:oauth:grant-type:token-exchange" \
            --data-urlencode "subject_token_type=urn:ietf:params:oauth:token-type:jwt" \
            --data-urlencode "requested_token_type=urn:opc:token-type:upst" \
            --data-urlencode "subject_token=$ID_TOKEN" \
            --data-urlencode "scope=urn:opc:idm:__myscopes__")

          echo "Resposta do Token Exchange:"
          echo "$TOKEN_RESPONSE" | jq

          ACCESS_TOKEN=$(echo "$TOKEN_RESPONSE" | jq -r '.access_token')

          echo "::add-mask::$ACCESS_TOKEN"
          echo "UPST=$ACCESS_TOKEN" >> $GITHUB_ENV

      - name: Testar chamada na API OCI com UPST
        run: |
          echo "Chamando API da OCI com o UPST..."
          curl -s -X GET \
            -H "Authorization: Bearer $UPST" \
            -H "Content-Type: application/json" \
            "https://identity.us-ashburn-1.oraclecloud.com/20160918/users/" | jq
