name: OCI Token Exchange (GitHub OIDC → UPST)

on:
  push:

permissions:
  id-token: write   # GitHub precisa disso pra emitir o OIDC JWT
  contents: read

jobs:
  exchange-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install OCI CLI
        run: |
          curl -L https://raw.githubusercontent.com/oracle/oci-cli/master/scripts/install/install.sh \
            | bash -s -- --accept-all-defaults
          echo "$HOME/bin" >> $GITHUB_PATH

      - name: Exchange GitHub OIDC → OCI UPST
        uses: gtrevorrow/oci-token-exchange-action@v1
        with:
          oidc_client_identifier: ${{ secrets.OIDC_CLIENT_IDENTIFIER }}   # "client_id:client_secret"
          domain_base_url: ${{ vars.DOMAIN_BASE_URL }}
          oci_tenancy: ${{ vars.OCI_TENANCY }}
          oci_region: ${{ vars.OCI_REGION }}
          oci_profile: DEFAULT
          # debug: true

      - name: Sanity check - get namespace
        run: |
          oci --auth security_token --profile DEFAULT os ns get


