name: OCI Token Exchange via GitHub OIDC

on:
  workflow_dispatch:  # para executar manualmente

permissions:
  id-token: write     # para emitir token OIDC do GitHub
  contents: read

jobs:
  exchange-token:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Obter ID Token do GitHub OIDC
        id: oidc
        run: |
          echo "Solicitando token OIDC..."
          TOKEN_JSON=$(curl -sSL "$ACTIONS_ID_TOKEN_REQUEST_URL" \
            -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN")

          ID_TOKEN=$(echo "$TOKEN_JSON" | jq -r .value)
          echo "::add-mask::$ID_TOKEN"
          echo "ID_TOKEN=$ID_TOKEN" >> $GITHUB_ENV

          echo "Decodificando o payload do ID Token:"
          PAYLOAD=$(echo "$ID_TOKEN" | cut -d '.' -f2 | tr '_-' '/+' | base64 -d 2>/dev/null || echo "INVALID_PAYLOAD")
          echo "$PAYLOAD" | jq || echo "Payload inválido ou malformado"

      - name: Fazer Token Exchange na OCI para obter UPST
        id: upst
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}          # Coloque seu Client ID aqui no GitHub Secrets
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}  # E o Client Secret aqui
          ID_TOKEN: ${{ env.ID_TOKEN }}
        run: |
          echo "Trocando token via Identity Domain da OCI..."

          AUTH_HEADER=$(echo -n "$CLIENT_ID:$CLIENT_SECRET" | base64)

          TOKEN_RESPONSE=$(curl -s -X POST \
            "https://idcs-c3fbb3ae829b4af0a98995e5f1549f09.identity.oraclecloud.com/oauth2/v1/token" \
            -H "Content-Type: application/x-www-form-urlencoded;charset=utf-8" \
            -H "Authorization: Basic $AUTH_HEADER" \
            --data-urlencode "grant_type=urn:ietf:params:oauth:grant-type:token-exchange" \
            --data-urlencode "subject_token_type=urn:ietf:params:oauth:token-type:jwt" \
            --data-urlencode "requested_token_type=urn:opc:token-type:upst" \
            --data-urlencode "subject_token=$ID_TOKEN")

          echo "Resposta do Token Exchange:"
          echo "$TOKEN_RESPONSE" | jq

          ACCESS_TOKEN=$(echo "$TOKEN_RESPONSE" | jq -r '.access_token')

          if [ "$ACCESS_TOKEN" = "null" ] || [ -z "$ACCESS_TOKEN" ]; then
            echo "Falha ao obter o token UPST"
            exit 1
          fi

          echo "::add-mask::$ACCESS_TOKEN"
          echo "UPST=$ACCESS_TOKEN" >> $GITHUB_ENV

      - name: Testar chamada na API OCI com o UPST
        run: |
          echo "Chamando API da OCI com o UPST..."
          curl -s -X GET \
            -H "Authorization: Bearer $UPST" \
            -H "Content-Type: application/json" \
            "https://identity.us-ashburn-1.oraclecloud.com/20160918/users/" | jq