name: OCI Token Exchange via GitHub OIDC

on:
  workflow_dispatch:  # para executar manualmente

permissions:
  id-token: write     # para emitir token OIDC do GitHub
  contents: read

jobs:
  exchange-token:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Obter ID Token do GitHub OIDC
        id: oidc
        run: |
          echo "Solicitando token OIDC..."
          TOKEN_JSON=$(curl -sSL "$ACTIONS_ID_TOKEN_REQUEST_URL" \
            -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN")

          ID_TOKEN=$(echo "$TOKEN_JSON" | jq -r .value)
          echo "::add-mask::$ID_TOKEN"
          echo "ID_TOKEN=$ID_TOKEN" >> $GITHUB_ENV

          echo "Decodificando o payload do ID Token:"
          PAYLOAD=$(echo "$ID_TOKEN" | cut -d '.' -f2 | tr '_-' '/+' | base64 -d 2>/dev/null || echo "INVALID_PAYLOAD")
          echo "$PAYLOAD" | jq || echo "Payload inválido ou malformado"

      - name: Fazer Token Exchange na OCI para obter UPST
        id: upst
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}          # Coloque seu Client ID aqui no GitHub Secrets
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}  # E o Client Secret aqui
          ID_T_

